### ISSUE TITLE
Apple Account authentication via Fido key won't pass the PIN code stage

### ISSUE THREAD

**Issue by rshimoda** [XcodesOrg/XcodesApp#704]
**Describe the bug**
When authenticating to an Apple Account with hardware security key enabled, the authentication is failed after entering the key's PIN code.

**To Reproduce**
1. Sign in into Apple Account with hardware authentication keys enabled
2. When promted, insert the hardware key and enter the PIN code

**Expected behavior**
The key is recognized and authentication process continues (the next step should be "touch the key").

**Screenshots**
![Image](https://github.com/user-attachments/assets/7676833b-3369-4f65-af4b-fc093a1a5c8c)

**Version**
 - OS: 15.4
 - Xcodes: 2.4.1 (30)

**Comment by rshimoda** [comment]
I fixed this by updating `LibFido2Swift`, waiting for approve.

**Comment by MattKiazyk** [comment]
v2.4.2 is available and should fix your issue! Thanks

**Comment by JanRajtr** [comment]
Unfortunately this is still not fixed on version 2.4.2. Just another error is thrown:

<img width="253" alt="Image" src="https://github.com/user-attachments/assets/d07d32e2-4678-4df7-b73a-a020d5bdc6a0" />

**Comment by JanRajtr** [comment]
Unfortunately this is still not fixed on version 2.4.2. Just another error is thrown:

<img width="253" alt="Image" src="https://github.com/user-attachments/assets/d07d32e2-4678-4df7-b73a-a020d5bdc6a0" />
